### ISSUE TITLE
Covid-19 Food Map

### ISSUE THREAD

**Issue by elburnett** [OpenMaine/project-ideas#3]
### What problem are you trying to solve?

[A lot of pantries and food distribution centers are changing their hours and practices rapidly. It's hard to keep up, and info is siloed by county or town]

### In less than 140 characters explain your idea?

[Create a map with crowdsourced data to collect info statewide for people needing food.]

### Who will benefit from your project? Can you tell their story?

[Anyone who is looking for food and can't get it either because they can't afford it or because it has run out]

### What area of Civic Engagement would you put this under? [1 or more]

- Disaster and Humanitiarian Relief

### What other resources/tools are currently serving the same need? 

[https://www.gsfb.org/get-help/food-map/]

### Are there any Drawbacks to choosing this path?

[It would be better if we could help good shephard update theirs]

### What would success look like?

[Getting it shared and used by many people. Getting buy-in and support from agencies who need help getting food to people.]

### What help do you need now?

[Mapping, data aggregation]

### What are the next steps (validation, research, coding, design)?

[Getting answers from cumberland county food security council on statewide coordination efforts. Then research + data]

----

**Comment by abutcher207** [comment]
Food pantries represent one portion of a supply chain.  A receiving portal for delivery and distribution of food.  Mapping locations will be great.  I'd be curious to also inventory cultural institutions, non-profits, restaurants, food service providers, and hospitality businesses to get a sense of what assets, facilities, personnel, etc could be leveraged to support and compliment the needs and function of the supply chain.  

If we can inventory that swatch of entities as well as local government and social service providers how can we best facilitate a match making where possible.  An online "service market place" comes to mind.  I feel silly as something simple must already exist along those lines (that isn't Amazon.)

**Comment by elburnett** [comment]
@abutcher207 check out this website: https://helpwithcovid.com/projects

**Comment by congdon** [comment]
Closing this 'project-idea issue', since I just created the covid19-foodmap actual project. Lots to be built out there...

**Comment by abutcher207** [comment]
Thanks
________________________________
