### ISSUE TITLE
UI Eligibility Determination Tool: COVID

### ISSUE THREAD

**Issue by elburnett** [OpenMaine/project-ideas#4]
### What problem are you trying to solve?

A lot of people are unclear on whether/if they meet the requirements to apply, and the legislature just changed some rules.

### In less than 140 characters explain your idea?

Create a simple conditional tool (either a website or could probably use Typeform) to determine whether someone should apply. 

### Who will benefit from your project? Can you tell their story?

People who need unemployment insurance from the state 

### What area of Civic Engagement would you put this under? [1 or more]

- Poverty Alleviation 
- Social Services

### What other resources/tools are currently serving the same need? 

The state's UI system. But it's very clunky, and you need to create an account. Plus hundreds if not thousands could be using the system at the same time, crashing it. 

### Is there any data, research or code available for your current idea?

I did one of these for Maine Equal Justice 

### Are there any Drawbacks to choosing this path?

If it's inaccurate, it could be really harmful

### What would success look like?

Having thousands of people use it. Can get social service agencies to share, potentially even the state gov

### What help do you need now?

Collaborators; expert help in building

### What are the next steps (validation, research, coding, design)?

See who can help, and who can be accurate source of info

----

**Comment by congdon** [comment]
Nice work!

Suggestion: edit to call this Unemployment Compensation (not 'insurance').

**Comment by elburnett** [comment]
I also got info from someone in Government who suggested we shouldnt' do this project because the details change way too quickly.

**Comment by congdon** [comment]
Created a new covid19-unemployment project; ideas should collect there.
